pretrained_model_name_or_path: 'stabilityai/stable-diffusion-2-1-unclip'
revision: null
pretrained_unet_path: null
# pretrained_unet_path: null # '/mnt/pfs/users/longxiaoxiao/workplace/wonder3Dplus/outputs-512/ortho/mvdiffusion-mix-random2views/unet-20000/'
num_views: 8
data_view_num: 8
data_path: '/home/czh5/multimodal/deepspeed-mvdiffusion/data'
train_dataset:
  root_dir: '/home/czh5/multimodal/deepspeed-mvdiffusion/data/' #'/blob1/3rdparty/obj-render1/objaverse/hf-objaverse-v1/'
  object_list: ${data_path}/data_valid_1231.json
  #invalid_list: null #'./data_lists/lvis/lvis-invalid-512.json'
  num_views: ${num_views}
  random_views: true # modify
  data_view_num: ${data_view_num}
  groups_num: 1
  bg_color: 'three_choices'
  img_wh: [384, 384]
  suffix: 'png'
  subscene_tag: 0
  validation: false
  num_validation_samples: 8
  random_scale: false
  # read_normal: true
  # read_color: true
  read_mask: true
  mix_color_normal: true
validation_dataset:
  root_dir: '/home/czh5/multimodal/deepspeed-mvdiffusion/data/' #'/blob1/3rdparty/obj-render1/objaverse/hf-objaverse-v1/'
  object_list: ${data_path}/data_valid_1231.json
  num_views: ${num_views}
  random_views: false
  data_view_num: ${data_view_num}
  bg_color: 'white'
  img_wh: [384, 384]
  suffix: 'png'
  subscene_tag: 0
  groups_num: 1
  validation: true
  num_validation_samples: 8
  random_scale: false
  # read_normal: true
  # read_color: true
  read_mask: true
  mix_color_normal: true
validation_train_dataset:
  root_dir: '/home/czh5/multimodal/deepspeed-mvdiffusion/data/' #'/blob1/3rdparty/obj-render1/objaverse/hf-objaverse-v1/'
  object_list: ${data_path}/data_valid_1231.json
  #invalid_list: './data_lists/lvis/lvis-invalid-384.json'
  num_views: ${num_views}
  random_views: false
  data_view_num: ${data_view_num}
  bg_color: 'white'
  img_wh: [384, 384]
  suffix: 'png'
  subscene_tag: 0
  validation: true
  num_validation_samples: 8
  num_samples: 8
  random_scale: false
  # read_normal: true
  # read_color: true
  read_mask: true
  mix_color_normal: true

pred_type: 'mix'

output_dir: 'outputs-384/unclip-8views0207real-emberlrx1-5e-5-continue-20k'
seed: 42
train_batch_size: 4
validation_batch_size: 1
validation_train_batch_size: 1
max_train_steps: 4
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 5.e-5
scale_lr: false
lr_scheduler: "constant_with_warmup"
lr_warmup_steps: 100
snr_gamma: 5.0
use_8bit_adam: false
allow_tf32: true
use_ema: true  
dataloader_num_workers: 64
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.e-2
adam_epsilon: 1.e-08
max_grad_norm: 1.0
prediction_type: null
vis_dir: vis
logging_dir: logs
mixed_precision: "fp16"  # seems mixed_precision cause inf training problem
report_to: 'tensorboard'
local_rank: -1
checkpointing_steps: 2500
checkpoints_total_limit: 20
resume_from_checkpoint: latest #  latest  # modify
enable_xformers_memory_efficient_attention: true
validation_steps: 100000
validation_sanity_check: false
tracker_project_name: 'mvdiffusion-image-v1'

trainable_modules: null # ['joint_mid']

use_classifier_free_guidance: true
condition_drop_rate: 0.05
drop_type: 'drop_as_a_whole'  # modify
camera_embedding_lr_mult: 1.
scale_input_latents: true

pipe_kwargs:
  # camera_embedding_type: 'e_de_da_sincos'
  num_views: ${num_views}

validation_guidance_scales: [1., 3.]
pipe_validation_kwargs:
  eta: 1.0
validation_grid_nrow: 16

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  unclip: true
  # encoder_hid_dim_type: 'text_proj'
  # encoder_hid_dim: 1024  # 1024+10
  # projection_class_embeddings_input_dim: 10  # modify
  num_views: ${num_views}
  sample_size: 48 # 32 for res256
  zero_init_conv_in: true
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: false
  multiview_attention: true
  sparse_mv_attention: true
  mvcd_attention: false

# num_views: ${num_views}
# camera_embedding_type: 'e_de_da_sincos'
